export {
  pulseVariants,
  bounceVariants,
  spinVariants,
  hoverScaleVariants,
  hoverRotateVariants,
  wiggleVariants,
  glowPulseVariants,
  floatVariants,
  shakeVariants,
  clickVariants,
  badgePulseVariants,
  fadeInVariants,
  colorShiftVariants,
} from './icon-animations';
